# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to='pics/', verbose_name='Select Picture')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('Bio', models.TextField(blank=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('owner_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_follow', models.ManyToManyField(blank=True, default=False, through='gram.Follow', to='gram.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(default=False, related_name='comments', through='gram.Comment', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.Profile'),
        ),
    ]
