# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20180511_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_by',
            new_name='owner_profile',
        ),
    ]
